// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/laojiawei/0_Data/1_workPlace/0_my/enjoy-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from '/Users/laojiawei/0_Data/1_workPlace/0_my/enjoy-ui/node_modules/dumi/theme-default/slots/SearchBar/index.js';
